name: ai-autoupdate
on:
  schedule: [{ cron: "*/60 * * * *" }] # hourly; tune as needed
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  update-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, ref: main }
      - name: Set up Node (for your threejs build checks later)
        uses: actions/setup-node@v4
        with: { node-version: "20" }

      # Aider-in-a-box; will edit files in-place
      - name: Run Aider (AI maintainer)
        uses: mirrajabi/aider-github-action@v1.1.0
        timeout-minutes: 12
        with:
          api_key_env_name: OPENAI_API_KEY
          api_key_env_value: ${{ secrets.OPENAI_API_KEY }}
          model: gpt-5
          branch: main
          aider_args: >
            --yes
            --no-gitignore
            --map-tokens 4096
            --message "
            You are an autonomous maintainer for a Three.js multiplayer fantasy web app.
            Each run ships ONE small, production-ready change that works immediately.
        
            Detect entry in this order:
              1) index.html <script type='module' src='...'>
              2) package.json main/module/scripts hints
              3) app.js file that sets up renderer/scene/animate
        
            Rules:
              - Create/modify files as needed; never ask to 'add' files.
              - Export from new modules; no top-level side effects on import.
              - Import and initialize the new feature exactly once in the detected entry after the app/scene is ready.
              - Keep controls/camera/networking intact; don’t steal focus.
              - Scope UI styles via class names; avoid global selector collisions.
              - Fix all import paths; ensure build passes.
              - If risky, downscope to a safer fix.
            Deliverables:
              - Working, wired feature (visible/verifiable immediately).
              - One-line README changelog.
              - Commit message: feat:/fix: concise.
            "

      # Optional: quick sanity checks before commit
      - name: Install deps & check build
        run: |
          npm ci || npm i
          npm run lint --if-present
          npm test --if-present
          npm run build --if-present

      - name: Commit & push to main if changed
        run: |
          git config user.name "ai-bot"
          git config user.email "ai-bot@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "AI: incremental updates"
            git push origin HEAD:main
          else
            echo "No changes."
          fi
