name: ai-autoupdate
on:
  schedule: [{ cron: "*/60 * * * *" }] # hourly; tune as needed
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  update-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, ref: main }
      - name: Set up Node (for your threejs build checks later)
        uses: actions/setup-node@v4
        with: { node-version: "20" }

      # Aider-in-a-box; will edit files in-place
      - name: Run Aider (AI maintainer)
        uses: mirrajabi/aider-github-action@v1.1.0
        timeout-minutes: 12
        with:
          api_key_env_name: OPENAI_API_KEY
          api_key_env_value: ${{ secrets.OPENAI_API_KEY }}
          model: gpt-4o-mini
          branch: main
          aider_args: >
            --yes
            --message "For this run, make a trivial, safe change to prove the loop works:
            append a 'Last updated by AI: <date>' line to README.md. Keep build passing."


      # Optional: quick sanity checks before commit
      - name: Install deps & check build
        run: |
          npm ci || npm i
          npm run lint --if-present
          npm test --if-present
          npm run build --if-present

      - name: Commit & push to main if changed
        run: |
          git config user.name "ai-bot"
          git config user.email "ai-bot@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "AI: incremental updates"
            git push origin HEAD:main
          else
            echo "No changes."
          fi
